[package]
name = "doix"
version = "0.1.0"
authors = ["arekbal <arek_bal@wp.pl>"]
build = "build.rs"
publish = false

[dependencies]
gl = "0.6.0"
rand = "0.3.16"
bitflags = "1.0.1"

[build-dependencies]
gl_generator = "0.5.0"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["ttf","image", "unsafe_textures"]
git = "https://github.com/Rust-SDL2/rust-sdl2.git"
branch = "unsafe-textures-feature"